Repository UB-ES-2018/instagram, pull requests merged in 2018-11, with the labels that each got.

#84 [service] agregado servicio
  instagram-services/src/main/java/instagram/controller/BaseController.java
  instagram-services/src/main/java/instagram/controller/CommentController.java
  instagram-services/src/main/java/instagram/controller/FollowerController.java
  instagram-services/src/main/java/instagram/controller/HashTagController.java
  instagram-services/src/main/java/instagram/controller/LikeController.java
  instagram-services/src/main/java/instagram/controller/PostController.java
  instagram-services/src/main/java/instagram/controller/PostTagController.java
  instagram-services/src/main/java/instagram/service/FollowerService.java
  instagram-services/src/main/java/instagram/service/impl/FollowerServiceImpl.java
Labels: back-end

#86 first
  instagram-services/res/bbdd/bbdd-instagram-dummies.sql
  instagram-services/src/main/java/instagram/controller/HashTagController.java
  instagram-services/src/main/java/instagram/controller/LikeController.java
  instagram-services/src/main/java/instagram/controller/PostTagController.java
  instagram-services/src/main/java/instagram/model/Post.java
  instagram-services/src/main/java/instagram/service/impl/CommentServiceImpl.java
Labels: BBDD, back-end

#92 [service, ui] se ha implementado la verificacion de la password en el…
  Instagram-ui/src/app/const/const.ts
  Instagram-ui/src/app/secured/edit-user-profile/edit-password/edit-password.component.ts
  Instagram-ui/src/app/service/user.service.ts
  instagram-services/src/main/java/instagram/controller/UserController.java
  instagram-services/src/main/java/instagram/service/UserService.java
  instagram-services/src/main/java/instagram/service/impl/UserServiceImpl.java
Labels: back-end, front-end

#95 Issue 90
  Instagram-ui/src/app/const/const.ts
  Instagram-ui/src/app/model/passDto.ts
  Instagram-ui/src/app/secured/edit-user-profile/edit-profile-data/edit-profile-data.component.ts
  Instagram-ui/src/app/service/user.service.ts
  instagram-services/src/main/java/instagram/controller/dto/PassChangerDto.java
Labels: back-end, front-end

#104 Se ha completado US2.1
  Instagram-ui/src/app/const/const.ts
  Instagram-ui/src/app/secured/profile/profile.component.html
  Instagram-ui/src/app/secured/profile/profile.component.spec.ts
  Instagram-ui/src/app/secured/profile/profile.component.ts
  Instagram-ui/src/app/service/follow.service.ts
  instagram-services/res/bbdd/bbdd-instagram-dummies.sql
  instagram-services/src/main/java/instagram/controller/FollowerController.java
  instagram-services/src/main/java/instagram/service/FollowerService.java
  instagram-services/src/main/java/instagram/service/impl/FollowerServiceImpl.java
Labels: back-end, front-end

#116 [service, ui] agregado servicio indicado en la issue, en la ui se ha …
  Instagram-ui/src/app/app.module.ts
  Instagram-ui/src/app/const/const.ts
  Instagram-ui/src/app/model/Coment.ts
  Instagram-ui/src/app/model/PostLoad.ts
  Instagram-ui/src/app/secured/profile/profile.component.ts
  Instagram-ui/src/app/service/post.service.ts
  instagram-services/src/main/java/instagram/controller/PostController.java
  instagram-services/src/main/java/instagram/controller/dto/PostLoadDto.java
  instagram-services/src/main/java/instagram/model/CommentLoad.java
  instagram-services/src/main/java/instagram/model/LikesCommentAux.java
  instagram-services/src/main/java/instagram/model/PostLoad.java
  instagram-services/src/main/java/instagram/repository/LikesCommentAuxRepository.java
  instagram-services/src/main/java/instagram/service/LikesComentAuxService.java
  instagram-services/src/main/java/instagram/service/PostService.java
  instagram-services/src/main/java/instagram/service/UserService.java
  instagram-services/src/main/java/instagram/service/impl/LikesComentAuxServiceImpl.java
  instagram-services/src/main/java/instagram/service/impl/PostServiceImpl.java
  instagram-services/src/main/java/instagram/service/impl/UserServiceImpl.java
Labels: back-end, front-end

#118 Merge 108 a 117
  Instagram-ui/src/app/secured/profile/profile.component.ts
  Instagram-ui/src/assets/images/3dots_logo.png
  Instagram-ui/src/assets/images/bookmark_logo.png
  Instagram-ui/src/assets/images/comment_logo.png
  Instagram-ui/src/assets/images/insta_icons.png
  Instagram-ui/src/assets/images/like_logo.png
  Instagram-ui/src/index.html
  Instagram-ui/src/styles/bootstrap/_buttons.scss
  Instagram-ui/src/styles/bootstrap/_custom.scss
  Instagram-ui/src/styles/bootstrap/_modal.scss
  Instagram-ui/src/styles/bootstrap/bootstrap.scss
  Instagram-ui/src/styles/insta_icons.png
Labels: front-end

#120 [service,ui] servicio para retornar fotos
  Instagram-ui/src/app/const/const.ts
  Instagram-ui/src/app/model/PostPerfil.ts
  Instagram-ui/src/app/secured/profile/profile.component.ts
  Instagram-ui/src/app/service/post.service.ts
  instagram-services/src/main/java/instagram/controller/PostController.java
  instagram-services/src/main/java/instagram/controller/dto/PostPerfilDto.java
  instagram-services/src/main/java/instagram/model/PostPerfil.java
  instagram-services/src/main/java/instagram/repository/LikeRepository.java
  instagram-services/src/main/java/instagram/service/LikeService.java
  instagram-services/src/main/java/instagram/service/PostService.java
  instagram-services/src/main/java/instagram/service/impl/LikeServiceImpl.java
  instagram-services/src/main/java/instagram/service/impl/PostServiceImpl.java
Labels: back-end, front-end

#121 [bbdd, service]
  Instagram-ui/src/app/const/const.ts
  Instagram-ui/src/app/model/PostLoad.ts
  Instagram-ui/src/app/model/User.ts
  Instagram-ui/src/app/service/user.service.ts
  instagram-services/res/bbdd/bbdd-instagram-dummies.sql
  instagram-services/res/bbdd/bbdd-instagram.sql
  instagram-services/res/bbdd/instagram-v1.mwb
  instagram-services/src/main/java/instagram/controller/PostController.java
  instagram-services/src/main/java/instagram/controller/UserController.java
  instagram-services/src/main/java/instagram/controller/dto/PostLoadDto.java
  instagram-services/src/main/java/instagram/controller/dto/UserDto.java
  instagram-services/src/main/java/instagram/model/PostLoad.java
  instagram-services/src/main/java/instagram/model/User.java
  instagram-services/src/main/java/instagram/service/PostService.java
  instagram-services/src/main/java/instagram/service/UserService.java
  instagram-services/src/main/java/instagram/service/impl/PostServiceImpl.java
  instagram-services/src/main/java/instagram/service/impl/UserServiceImpl.java
Labels: BBDD, back-end, front-end

#122 afegit feedback a la hora de pujar foto i implementada la càrrega de …
  Instagram-ui/src/app/secured/profile/profile.component.html
  Instagram-ui/src/app/secured/profile/profile.component.scss
  Instagram-ui/src/app/secured/profile/profile.component.ts
  Instagram-ui/src/app/service/post.service.ts
Labels: front-end

#126 Issue 105
  Instagram-ui/src/app/const/const.ts
  instagram-services/src/main/java/instagram/controller/CommentController.java
  instagram-services/src/main/java/instagram/controller/CommentLikeController.java
  instagram-services/src/main/java/instagram/controller/LikeController.java
  instagram-services/src/main/java/instagram/controller/dto/CommentLikeDto.java
  instagram-services/src/main/java/instagram/exception/ErrorCodes.java
  instagram-services/src/main/java/instagram/model/CommentLike.java
  instagram-services/src/main/java/instagram/repository/CommentLikeRepository.java
  instagram-services/src/main/java/instagram/repository/LikeRepository.java
  instagram-services/src/main/java/instagram/service/CommentLikeService.java
  instagram-services/src/main/java/instagram/service/LikeService.java
  instagram-services/src/main/java/instagram/service/impl/CommentLikeServiceImpl.java
  instagram-services/src/main/java/instagram/service/impl/CommentServiceImpl.java
  instagram-services/src/main/java/instagram/service/impl/LikeServiceImpl.java
Labels: back-end
